version: "3.5"

services:
  db:
      image: 'postgres:latest'
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres 
        POSTGRES_PASSWORD: password 
        POSTGRES_DB: shopping-lists-bot
      volumes:
        - ./.db-mount:/var/lib/postgresql/data/
